# Header
menu:
  Home: /
  NeoID3: /neoid3
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics:
baidu_analytics: 1c4a8ec51af12949dd6b46712e821b53
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id: